#!/usr/bin/env bash
# Generated by cgraf78/actions checkout Bash resolver. Do not edit.
# shellcheck shell=bash
# Shared Bash runtime resolver v1.
#
# The checkout installer embeds this fragment because a piped first-stage
# installer cannot source files from a checkout that does not exist yet. The
# renderer also publishes these exact function bytes as
# support/checkout-bash-v1.sh so a checkout-owned trampoline can use the same
# selection and validation contract. Keep this file compatible with stock
# macOS Bash 3.2 and free of consumer-specific policy.

_checkout_bash_v1_error() {
  printf 'checkout Bash resolver: %s\n' "$*" >&2
}

_checkout_bash_v1_normalized_absolute() {
  case $1 in
    '' | / | */ | *//* | */./* | */. | */../* | */.. | *$'\n'* | *$'\r'*)
      return 1
      ;;
    /*) return 0 ;;
    *) return 1 ;;
  esac
}

_checkout_bash_v1_probe() {
  local candidate=$1 output major

  _checkout_bash_v1_normalized_absolute "$candidate" || return 1
  [[ -f "$candidate" && -x "$candidate" ]] || return 1
  # shellcheck disable=SC2016 # Expanded only by the candidate interpreter.
  output=$(BASH_ENV='' ENV='' "$candidate" --noprofile --norc -c \
    'printf "cgraf78-checkout-bash-v1:%s\n" "${BASH_VERSINFO[0]-}"' \
    2>/dev/null) || return 1
  case $output in
    cgraf78-checkout-bash-v1:*) major=${output#*:} ;;
    *) return 1 ;;
  esac
  [[ "$major" =~ ^[0-9]+$ && "$major" -ge 4 ]] || return 1
}

_checkout_bash_v1_hint_path() {
  local namespace=$1 state_root

  case $namespace in
    '' | . | .. | *[!A-Za-z0-9._-]*)
      _checkout_bash_v1_error "invalid state namespace: $namespace"
      return 2
      ;;
  esac
  if [[ -n ${XDG_STATE_HOME:-} ]]; then
    state_root=$XDG_STATE_HOME
  else
    [[ -n ${HOME:-} ]] || {
      _checkout_bash_v1_error 'HOME is required when XDG_STATE_HOME is unset'
      return 1
    }
    state_root=$HOME/.local/state
  fi
  _checkout_bash_v1_normalized_absolute "$state_root" || {
    _checkout_bash_v1_error "state root must be a normalized absolute path: $state_root"
    return 1
  }
  printf '%s/%s/bash-v1\n' "$state_root" "$namespace"
}

_checkout_bash_v1_read_hint() {
  local hint=$1 header interpreter _extra='' size parse_ok=true

  [[ -e "$hint" || -L "$hint" ]] || return 1
  if [[ ! -f "$hint" || -L "$hint" ]]; then
    _checkout_bash_v1_error "refusing non-regular runtime hint: $hint"
    return 2
  fi
  size=$(wc -c <"$hint" 2>/dev/null) || size=
  size=${size//[[:space:]]/}
  case $size in
    '' | *[!0-9]*) size=4097 ;;
  esac
  if [[ ${#size} -gt 4 || "$size" -gt 4096 ]]; then
    _checkout_bash_v1_error "malformed runtime hint: $hint"
    return 2
  fi
  {
    IFS= read -r header || parse_ok=false
    IFS= read -r interpreter || parse_ok=false
    if IFS= read -r _extra || [[ -n "$_extra" ]]; then
      parse_ok=false
    fi
  } <"$hint"
  if [[ "$parse_ok" != true ]]; then
    _checkout_bash_v1_error "malformed runtime hint: $hint"
    return 2
  fi
  if [[ "$header" != 'cgraf78 checkout Bash runtime v1' ]] ||
    ! _checkout_bash_v1_normalized_absolute "$interpreter"; then
    _checkout_bash_v1_error "malformed runtime hint: $hint"
    return 2
  fi
  printf '%s\n' "$interpreter"
}

_checkout_bash_v1_detect_link_tool() {
  local parent=$1 probe source ln_bin mv_bin move_source='' move_target=''
  local move_destination nested mv_supported=false

  ln_bin=$(type -P ln 2>/dev/null) || return 1
  probe=$(mktemp -d "$parent/.bash-v1.tools.XXXXXX") || return 1
  source=$probe/source
  printf 'probe\n' >"$source"
  if "$ln_bin" -T -- "$source" "$probe/link" 2>/dev/null &&
    [[ "$source" -ef "$probe/link" ]]; then
    _CHECKOUT_BASH_V1_LN_MODE=T
  else
    rm -f "$probe/link"
    if "$ln_bin" -h "$source" "$probe/link" 2>/dev/null &&
      [[ "$source" -ef "$probe/link" ]]; then
      _CHECKOUT_BASH_V1_LN_MODE=h
    else
      rm -f "$probe/link"
      mv_bin=$(type -P mv 2>/dev/null) || mv_bin=
      move_source=$probe/move-source
      move_target=$probe/move-target
      move_destination=$probe/destination
      printf 'move probe\n' >"$move_source"
      if [[ -n "$mv_bin" ]] &&
        "$mv_bin" -nT -- "$move_source" "$move_target" 2>/dev/null &&
        [[ ! -e "$move_source" && ! -L "$move_source" &&
          -f "$move_target" && ! -L "$move_target" ]] &&
        mkdir "$move_destination"; then
        # GNU mv versions disagree about whether a preserved -n collision is
        # success or failure. The filesystem postcondition is the contract:
        # the source survives and the exact destination directory is untouched.
        "$mv_bin" -nT -- "$move_target" "$move_destination" 2>/dev/null || true
        if [[ -f "$move_target" && ! -L "$move_target" &&
          -d "$move_destination" && ! -L "$move_destination" ]] &&
          rmdir "$move_destination"; then
          mv_supported=true
        fi
      fi
      if [[ "$mv_supported" == true ]]; then
        _CHECKOUT_BASH_V1_LN_MODE=mv-T
        _CHECKOUT_BASH_V1_MV_BIN=$mv_bin
      else
        nested=$move_destination/${move_target##*/}
        rm -f "$nested" "$move_source" "$move_target" "$source"
        rmdir "$move_destination" 2>/dev/null || true
        rmdir "$probe" 2>/dev/null || true
        _checkout_bash_v1_error 'no exact-destination runtime-hint publication is available'
        return 1
      fi
    fi
  fi
  rm -f "$probe/link" "$source" "$move_source" "$move_target"
  rmdir "$probe" || return 1
  _CHECKOUT_BASH_V1_LN_BIN=$ln_bin
}

_checkout_bash_v1_link_exact() {
  case $_CHECKOUT_BASH_V1_LN_MODE in
    T) "$_CHECKOUT_BASH_V1_LN_BIN" -T -- "$1" "$2" ;;
    h) "$_CHECKOUT_BASH_V1_LN_BIN" -h "$1" "$2" ;;
    mv-T) "$_CHECKOUT_BASH_V1_MV_BIN" -nT -- "$1" "$2" ;;
    *) return 1 ;;
  esac
}

_checkout_bash_v1_cleanup_nested_link() {
  local container=$1 source=$2 nested

  [[ -d "$container" && ! -L "$container" ]] || return 0
  nested=$container/${source##*/}
  [[ -f "$nested" && ! -L "$nested" && "$nested" -ef "$source" ]] ||
    return 0
  rm -f "$nested"
}

_checkout_bash_v1_write_hint() {
  local hint=$1 interpreter=$2
  local parent temporary old_umask current status=0

  parent=${hint%/*}
  old_umask=$(umask)
  umask 077
  if ! mkdir -p "$parent" || [[ ! -d "$parent" || -L "$parent" ]] ||
    ! chmod 0700 "$parent"; then
    umask "$old_umask"
    _checkout_bash_v1_error "cannot create private runtime state: $parent"
    return 1
  fi

  if [[ -e "$hint" || -L "$hint" ]]; then
    current=$(_checkout_bash_v1_read_hint "$hint") || {
      umask "$old_umask"
      return 1
    }
    umask "$old_umask"
    _checkout_bash_v1_probe "$current"
    return
  fi

  _checkout_bash_v1_detect_link_tool "$parent" || {
    umask "$old_umask"
    return 1
  }
  temporary=$(mktemp "$parent/.bash-v1.XXXXXX") || {
    umask "$old_umask"
    _checkout_bash_v1_error "cannot allocate runtime hint beside: $hint"
    return 1
  }
  if ! printf 'cgraf78 checkout Bash runtime v1\n%s\n' "$interpreter" \
    >"$temporary" || ! chmod 0600 "$temporary"; then
    rm -f "$temporary"
    umask "$old_umask"
    _checkout_bash_v1_error "cannot publish runtime hint: $hint"
    return 1
  fi

  _checkout_bash_v1_link_exact "$temporary" "$hint" 2>/dev/null || status=$?
  if [[ ! -f "$hint" || -L "$hint" || ! "$hint" -ef "$temporary" ]]; then
    _checkout_bash_v1_cleanup_nested_link "$hint" "$temporary" || true
  fi
  rm -f "$temporary"
  umask "$old_umask"

  current=$(_checkout_bash_v1_read_hint "$hint") || {
    _checkout_bash_v1_error "runtime hint appeared during selection: $hint"
    return 1
  }
  if [[ "$current" == "$interpreter" ]] ||
    _checkout_bash_v1_probe "$current"; then
    return 0
  fi
  _checkout_bash_v1_error "published runtime hint did not verify: $hint"
  [[ "$status" -ne 0 ]] && return "$status"
  return 1
}

# Selects and persists one Bash 4+ interpreter.
#
# Usage: checkout_bash_v1_select STATE_NAMESPACE EXPLICIT_OVERRIDE
# Success sets CHECKOUT_BASH_V1_INTERPRETER and clears the runtime output until
# checkout_bash_v1_bind validates the exact script to execute. An explicit
# override is strict: an invalid override never falls back to another Bash.
checkout_bash_v1_select() {
  local namespace=${1:-} explicit=${2:-} hint hinted candidate path_entry
  local hint_present=false hint_selected=false path_remaining path_more

  CHECKOUT_BASH_V1_INTERPRETER=
  CHECKOUT_BASH_V1_RUNTIME=
  [[ $# -eq 2 ]] || {
    _checkout_bash_v1_error 'usage: checkout_bash_v1_select STATE_NAMESPACE EXPLICIT_OVERRIDE'
    return 2
  }
  hint=$(_checkout_bash_v1_hint_path "$namespace") || return $?

  if [[ -e "$hint" || -L "$hint" ]]; then
    hinted=$(_checkout_bash_v1_read_hint "$hint") || return 1
    hint_present=true
  fi

  if [[ -n "$explicit" ]]; then
    if ! _checkout_bash_v1_probe "$explicit"; then
      _checkout_bash_v1_error "explicit interpreter is not Bash 4 or newer: $explicit"
      return 1
    fi
    candidate=$explicit
  else
    if [[ -n ${hinted:-} ]] && _checkout_bash_v1_probe "$hinted"; then
      candidate=$hinted
      hint_selected=true
    fi

    if [[ -z ${candidate:-} ]] &&
      _checkout_bash_v1_probe "${BASH:-}"; then
      candidate=$BASH
    fi

    if [[ -z ${candidate:-} ]]; then
      path_remaining=${PATH-}
      while :; do
        case $path_remaining in
          *:*)
            path_entry=${path_remaining%%:*}
            path_remaining=${path_remaining#*:}
            path_more=true
            ;;
          *)
            path_entry=$path_remaining
            path_more=false
            ;;
        esac
        case $path_entry in
          /*) ;;
          *) path_entry= ;;
        esac
        if [[ -n "$path_entry" ]] &&
          _checkout_bash_v1_probe "$path_entry/bash"; then
          candidate=$path_entry/bash
          break
        fi
        [[ "$path_more" == true ]] || break
      done
    fi

    if [[ -z ${candidate:-} ]]; then
      if [[ -n ${PREFIX:-} ]] && _checkout_bash_v1_probe "$PREFIX/bin/bash"; then
        candidate=$PREFIX/bin/bash
      fi
    fi

    if [[ -z ${candidate:-} ]]; then
      for candidate in /opt/homebrew/bin/bash /usr/local/bin/bash \
        /opt/local/bin/bash /usr/bin/bash /bin/bash; do
        if _checkout_bash_v1_probe "$candidate"; then
          break
        fi
        candidate=
      done
    fi
  fi

  if [[ -z ${candidate:-} ]]; then
    _checkout_bash_v1_error 'Bash 4 or newer was not found; install it and retry'
    return 1
  fi
  if [[ "$hint_selected" != true && "$hint_present" != true ]]; then
    _checkout_bash_v1_write_hint "$hint" "$candidate" || return 1
  fi
  CHECKOUT_BASH_V1_INTERPRETER=$candidate
}

# Binds a selected interpreter to one exact checkout-relative runtime script.
#
# Usage: checkout_bash_v1_bind ABSOLUTE_RUNTIME
# Success publishes CHECKOUT_BASH_V1_INTERPRETER and CHECKOUT_BASH_V1_RUNTIME
# together. The interpreter is re-probed so replacement between selection and
# execution fails closed, and the runtime may not be a symlink.
checkout_bash_v1_bind() {
  local runtime=${1:-} interpreter=${CHECKOUT_BASH_V1_INTERPRETER:-}

  CHECKOUT_BASH_V1_INTERPRETER=
  CHECKOUT_BASH_V1_RUNTIME=
  [[ $# -eq 1 ]] || {
    _checkout_bash_v1_error 'usage: checkout_bash_v1_bind ABSOLUTE_RUNTIME'
    return 2
  }
  if ! _checkout_bash_v1_probe "$interpreter"; then
    _checkout_bash_v1_error 'selected Bash interpreter changed before execution'
    return 1
  fi
  if ! _checkout_bash_v1_normalized_absolute "$runtime" ||
    [[ ! -f "$runtime" || -L "$runtime" || ! -r "$runtime" ]]; then
    _checkout_bash_v1_error "runtime is not a readable regular file: $runtime"
    return 1
  fi
  CHECKOUT_BASH_V1_INTERPRETER=$interpreter
  # shellcheck disable=SC2034 # Public output consumed by the sourcing caller.
  CHECKOUT_BASH_V1_RUNTIME=$runtime
}
