# shellcheck shell=bash
# shellcheck disable=SC2034
CHECKOUT_INSTALLER_ENABLED=true
CHECKOUT_INSTALLER_REPO=cgraf78/dot
CHECKOUT_INSTALLER_DELEGATE=support/install-checkout.sh
CHECKOUT_INSTALLER_DEFAULT_DESTINATION=shdeps
CHECKOUT_INSTALLER_POST_INSTALL_DELEGATE=support/post-install.sh
CHECKOUT_INSTALLER_LOCK_PROTOCOL=v1
CHECKOUT_INSTALLER_BASH_RESOLVER=v1
CHECKOUT_INSTALLER_DEVELOPMENT_POLICY=shdeps
